"""добавил поле

Revision ID: 660dab64ac62
Revises: 07d3b38785df
Create Date: 2026-03-20 20:45:01.780534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660dab64ac62'
down_revision = '07d3b38785df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
